[project]
name = "neural_network_viz"
version = "0.1.0"
description = "Neural Network Training Visualization"
dependencies = [
    "streamlit>=1.29.0",
    "numpy>=1.24.0",
    "matplotlib>=3.7.0"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
